// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ToreVinc.Models;

#nullable disable

namespace ToreVinc.Migrations
{
    [DbContext(typeof(DbContextMuhasebe))]
    [Migration("20230613192353_TBL_KULLANICIBILGI1")]
    partial class TBL_KULLANICIBILGI1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ToreVinc.Models.Muhasebe.TBL_BANKABILGILERI", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("ADRES")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BANKAADI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BANKASUBESI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("DURUM")
                        .HasColumnType("bit");

                    b.Property<DateTime>("EDITDATE")
                        .HasColumnType("datetime2");

                    b.Property<int>("EDITUSER")
                        .HasColumnType("int");

                    b.Property<string>("EMAIL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HESAPNO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HESAPTURU")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IBAN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SAVEDATE")
                        .HasColumnType("datetime2");

                    b.Property<int>("SAVEUSER")
                        .HasColumnType("int");

                    b.Property<bool>("SIL")
                        .HasColumnType("bit");

                    b.Property<string>("SUBETELEFONU")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YETKILI")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("TBL_BANKABILGILERI");
                });

            modelBuilder.Entity("ToreVinc.Models.Muhasebe.TBL_KULLANICIBILGI", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<bool>("DURUM")
                        .HasColumnType("bit");

                    b.Property<string>("KULLANICIADI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SIFRE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("YONETICI")
                        .HasColumnType("bit");

                    b.HasKey("ID");

                    b.ToTable("TBL_KULLANICIBILGI");
                });
#pragma warning restore 612, 618
        }
    }
}
