// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ToreVinc.Models;

#nullable disable

namespace ToreVinc.Migrations
{
    [DbContext(typeof(DbContextMuhasebe))]
    [Migration("20230613193336_TBL_CEKLER")]
    partial class TBL_CEKLER
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ToreVinc.Models.Muhasebe.TBL_BANKABILGILERI", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("ADRES")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BANKAADI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BANKASUBESI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("DURUM")
                        .HasColumnType("bit");

                    b.Property<DateTime>("EDITDATE")
                        .HasColumnType("datetime2");

                    b.Property<int>("EDITUSER")
                        .HasColumnType("int");

                    b.Property<string>("EMAIL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HESAPNO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HESAPTURU")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IBAN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SAVEDATE")
                        .HasColumnType("datetime2");

                    b.Property<int>("SAVEUSER")
                        .HasColumnType("int");

                    b.Property<bool>("SIL")
                        .HasColumnType("bit");

                    b.Property<string>("SUBETELEFONU")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YETKILI")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("TBL_BANKABILGILERI");
                });

            modelBuilder.Entity("ToreVinc.Models.Muhasebe.TBL_CEKLER", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("ACIKLAMA")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ACKODU")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ALINANCARIID")
                        .HasColumnType("int");

                    b.Property<string>("ASILBORCLU")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BANKA")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BELGENO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BORDROID")
                        .HasColumnType("int");

                    b.Property<string>("CEKNO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DURUM")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EDITDATE")
                        .HasColumnType("datetime2");

                    b.Property<int>("EDITUSER")
                        .HasColumnType("int");

                    b.Property<string>("HESAPNO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SAVEDATE")
                        .HasColumnType("datetime2");

                    b.Property<int>("SAVEUSER")
                        .HasColumnType("int");

                    b.Property<string>("SUBE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TAHSIL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TARIH")
                        .HasColumnType("datetime2");

                    b.Property<string>("TIPI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TUTAR")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("VADETARIHI")
                        .HasColumnType("datetime2");

                    b.Property<string>("VERILENBANKA_BELGENO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VERILENBANKA_ID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("VERILENBANKA_TARIHI")
                        .HasColumnType("datetime2");

                    b.Property<int>("VERILENCARIID")
                        .HasColumnType("int");

                    b.Property<string>("VERILENCARI_BELGENO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("VERILENCARI_TARIHI")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.ToTable("TBL_CEKLER");
                });

            modelBuilder.Entity("ToreVinc.Models.Muhasebe.TBL_KULLANICIBILGI", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<bool>("DURUM")
                        .HasColumnType("bit");

                    b.Property<string>("KULLANICIADI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SIFRE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("YONETICI")
                        .HasColumnType("bit");

                    b.HasKey("ID");

                    b.ToTable("TBL_KULLANICIBILGI");
                });
#pragma warning restore 612, 618
        }
    }
}
