// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ToreVinc.Models;

#nullable disable

namespace ToreVinc.Migrations
{
    [DbContext(typeof(DbContextMuhasebe))]
    partial class DbContextMuhasebeModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ToreVinc.Models.Muhasebe.TBL_KULLANICIBILGI", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<bool>("DURUM")
                        .HasColumnType("bit");

                    b.Property<string>("KULLANICIADI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SIFRE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("YONETICI")
                        .HasColumnType("bit");

                    b.HasKey("ID");

                    b.ToTable("TBL_KULLANICIBILGI");
                });
#pragma warning restore 612, 618
        }
    }
}
